POST http://localhost:5000/newMessage HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJKb2huIiwidXNlcklkIjoyLCJyb2xlIjoiY3VzdG9tZXIiLCJsYXN0TmFtZSI6IkRvZSIsImF2YXRhciI6ImFub24ucG5nIiwiZGlzcGxheU5hbWUiOiJCdXllcm90dGkiLCJiYWxhbmNlIjoiMCIsImVtYWlsIjoiam9obi5kb2VAZ21haWwuY29tIiwicmF0aW5nIjowLCJpYXQiOjE3NTgxODYyMTcsImV4cCI6MTc1ODE4OTgxN30.K6jjZEbVAtSbxeNlh199Ca2EohKLTuuzsTBmGyewJOg
Content-Type: application/json

{
    "recipient": 1,
    "messageBody": "HEllo 123"
}